### ISSUE TITLE
Missing Sections and/or Chapters

### ISSUE THREAD

**Issue by atancasis** [PerlDancer/perldancer-book#2]
I realize the book may still be a work in progress. That said, attempting to build the book via `build/tools/build_chapters.pl` will fail while processing `sections/chapter_02.pod` as the sections listed there doesn't exist just yet. Issue created mainly for posterity.

**Comment by StylusEater** [comment]
Works OK now:

$ ./build/tools/build_chapters.pl
examples/hello_name.pl syntax OK
examples/hello_name_tt.pl syntax OK
examples/hello_name_tt_layout.pl syntax OK
examples/hello_world.pl syntax OK
examples/static_file.pl syntax OK
Writing 'build/chapters/chapter_00.pod'
Writing 'build/chapters/chapter_01.pod'
Writing 'build/chapters/chapter_02.pod'
