### ISSUE TITLE
no such Pod::PsuedoPod::HTML

### ISSUE THREAD

**Issue by itnomad** [PerlDancer/perldancer-book#9]
Can't find the module, Pod::PsuedoPod::HTML, which is required to build the book.

**Comment by StylusEater** [comment]
http://search.cpan.org/~chromatic/Pod-PseudoPod-0.18/lib/Pod/PseudoPod/HTML.pm

**Comment by StylusEater** [comment]
On Debian GNU/Linux I did the following:

## Installed Perlbrew
- `sudo su -`
- `apt-get install build-essential curl wget`
- `exit`
- `\curl -L http://install.perlbrew.pl | bash`
- `perlbrew install perl-blead`

## Installed cpanmin.us

`perlbrew install-cpanm`

## Installed Pod::PseudoPod::HTML

`cpanm -i  Pod::PseudoPod::HTML`

**Comment by StylusEater** [comment]
@itnomad Please confirm I can close the issue. Thanks.

**Comment by itnomad** [comment]
I'm using Perlbrew and cpanm. Today Pod::PseudoPod::HTML installed with no problem whereas the other day it could not be found. Thank you and please do close the issue.
